name: dondi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  #sdk: '>=3.0.0-198.0.dev <4.0.0'
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_messaging: ^14.2.6
  cloud_firestore: ^4.4.4
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.18
  http:
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  fluttertoast: ^8.2.1
  permission_handler: ^10.2.0
  audioplayers: ^0.20.1
  video_player: ^2.6.0
  flutter_downloader: ^1.10.2
  path_provider: ^2.0.13
  ffmpeg_kit_flutter_full: ^5.1.0
  image_picker: ^0.8.7
  flutter_video_info: ^1.3.1
  file_picker: ^5.2.6
  webview_flutter: ^4.2.0
  url_launcher: ^6.1.10
  shimmer: ^2.0.0
  visibility_detector: ^0.3.3
  cached_network_image: ^3.2.3
  video_thumbnail: ^0.5.3
  photo_view: ^0.14.0
  google_mobile_ads: ^2.3.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  bouncing_widget: ^2.0.0
  marquee: ^2.2.3
  app_tracking_transparency: ^2.0.3
  carousel_slider: ^4.2.1
  flutter_branch_sdk: ^6.6.0
  flutter_facebook_auth: ^5.0.8
  flutter_facebook_keyhash: ^0.0.4
  share_plus: ^6.3.1
  location: ^4.4.0
  dio: ^5.1.1
  agora_rtc_engine: ^6.1.0
  stacked: ^3.2.0
  wakelock: ^0.6.2
  http_parser: any
  bubbly_camera:
    path: "CameraPlugin/camera"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - icons/
    - images/


